# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b3cd298e85e47c8674267caf7f73ec1cd549d6a024d1fa244e8a59e8ce0ad4e095845da0b2a96c0100bf7ad74f67576724c31cbb88badc7430710f68ef2315

test:
  secret_key_base: a3412d6b2e822717ab61aec31c99ab5f7059cddfff270e4bd0ae15556ed48e273be737194874ca30da16035a37c8450230212191a7bfa1b06316d42171598d01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
